name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
version: VERSION
core: 8.x
hidden: true
install:
  - action
  - language
  - tour
