id: d6_contact_settings
label: Contact configuration
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: contact_settings
  variables:
    - contact_default_status
    - contact_hourly_threshold
process:
  user_default_enabled: contact_default_status
  'flood/limit': contact_hourly_threshold
  default_form:
    plugin: migration_lookup
    migration: contact_category
    source: default_category
destination:
  plugin: config
  config_name: contact.settings
migration_dependencies:
  required:
    - contact_category
