<?php
require('./includes/output.inc');
require('./includes/environment.inc');
require('./includes/command.inc');
require('./includes/drush.inc');
require('./includes/backend.inc');
require('./includes/batch.inc');
require('./includes/context.inc');
require('./includes/sitealias.inc');
require('./includes/exec.inc');
require('./includes/drupal.inc');
require('./includes/output.inc');
require('./includes/cache.inc');
require('./includes/filesystem.inc');
require('./includes/dbtng.inc');
require('./includes/bootstrap.inc');
require('drush.php');
?>