#!/usr/bin/env sh
# $Id$
#
# This script is a simple wrapper that will run Drush with the most appropriate
# php executable it can find.
#

# Get the absolute path of this executable
ORIGDIR=$(pwd)
SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")

# Resolve symlinks - this is the equivalent of "readlink -f", but also works with non-standard OS X readlink.
while [ -h "$SELF_PATH" ]; do
    # 1) cd to directory of the symlink
    # 2) cd to the directory of where the symlink points
    # 3) Get the pwd
    # 4) Append the basename
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink $SELF_PATH)
    SELF_PATH=$(cd $DIR && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done
cd "$ORIGDIR"

# Build the path to drush.php.
SCRIPT_PATH=$(dirname "$SELF_PATH")/drush.php
case $(uname -a) in
  CYGWIN*)
    SCRIPT_PATH=$(cygpath -w -a -- "$SCRIPT_PATH") ;;
esac

# prepend "--nocolor" to the argument list if stdout is not a terminal
if [ ! -t 1 ]; then
  set -- "--nocolor" ${1+"$@"}
fi

# If not exported, try to determine and export the number of columns.
if [ -z $COLUMNS ]; then
  # Note to cygwin users: install the ncurses package to get tput command.
  if COLUMNS=$(tput cols 2>/dev/null); then
    export COLUMNS
  fi
fi

# Default to using the php that we find on the PATH.
# Note that we need the full path to php here for Dreamhost, which behaves oddly.  See http://drupal.org/node/662926
php=`which php`

# We check for a command line (cli) version of php, and if found use that.
which php-cli >/dev/null 2>&1
if [ "$?" = 0 ] ; then
  php=`which php-cli`
fi

# Special case for *AMP installers, since they normally don't set themselves as the default cli php out of the box.
for amp_php in /Applications/MAMP/bin/php5/bin/php /Applications/MAMP/bin/php5.2/bin/php /Applications/MAMP/bin/php5.3/bin/php /opt/lampp/bin/php /Applications/xampp/xamppfiles/bin/php /Applications/acquia-drupal/php/bin/php; do
  if [ -x $amp_php ]; then
    php=$amp_php
  fi
done

# Check to see if the user has provided a php.ini file particularly for drush
if [ -f $HOME/.drush/php.ini ] ; then
  php="$php --php-ini $HOME/.drush/php.ini"
elif [ -f /etc/drush/php.ini ] ; then
  php="$php --php-ini /etc/drush/php.ini"
fi

# Pass in the path to php so that drush knows which one
# to use if it re-launches itself to run subcommands
exec $php "$SCRIPT_PATH" "$@" --php="$php"

