id: d6_forum_settings
label: Forum configuration
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: variable
  variables:
    - forum_hot_topic
    - forum_per_page
    - forum_order
    - forum_block_num_0
    - forum_block_num_1
    - forum_nav_vocabulary
  source_module: forum
process:
  'block/active/limit': forum_block_num_0
  'block/new/limit': forum_block_num_1
  'topics/hot_threshold': forum_hot_topic
  'topics/page_limit': forum_per_page
  'topics/order': forum_order
  vocabulary:
    plugin: migration_lookup
    migration: d6_taxonomy_vocabulary
    source: forum_nav_vocabulary
destination:
  plugin: config
  config_name: forum.settings
migration_dependencies:
  required:
    - d6_taxonomy_vocabulary
