blank_issues_enabled: false
contact_links:
  - name: 💬 Drush Slack
    url: https://drupal.slack.com/archives/C62H9CWQM
    about: Join the Drush Community to talk, exchange experiences or ask and answer questions.
  - name: 📒 Drupal Answers (powered by Stack Overflow)
    url: https://stackoverflow.com/questions/tagged/drush
    about: Support requests belong here.