# Schema for the configuration files of the Editor module.

editor.editor.*:
  type: config_entity
  label: 'Text editor'
  mapping:
    format:
      type: string
      label: 'Name'
    editor:
      type: string
      label: 'Text editor'
    settings:
      type: editor.settings.[%parent.editor]
    image_upload:
      type: mapping
      label: 'Image upload settings'
      mapping:
        status:
          type: boolean
          label: 'Status'
        scheme:
          type: string
          label: 'File storage'
        directory:
          type: string
          label: 'Upload directory'
        max_size:
          type: string
          label: 'Maximum file size'
        max_dimensions:
          type: mapping
          label: 'Maximum dimensions'
          mapping:
            width:
              type: integer
              nullable: true
              label: 'Maximum width'
            height:
              type: integer
              nullable: true
              label: 'Maximum height'
