<?php

/**
 * Good update.
 */
function woot_update_8101() {
  return t('This is the update message from woot_update_8101');
}

/**
 * Failing update.
 */
function woot_update_8102() {
  // This update fails by throwing an exception.
  throw new \Exception('This is the exception message thrown in woot_update_8102');
}

/**
 * Failing update 2.
 */
function woot_update_8103() {
  // This update fails by throwing a fatal error.
  non_existing_function();
}

/**
 * Another good update.
 */
function woot_update_8104() {
  // By using the theme system we can test that all Drupal modules are fully
  // loaded when the updates are being performed. The renderer will throw an
  // exception if this is not the case.
  $render_array = [
    '#theme' => 'item_list',
    '#items' => ['a', 'b'],
  ];
  \Drupal::service('renderer')->renderPlain($render_array);
  return t('This is the update message from woot_update_8104');
}

/**
 * Batch update.
 */
function woot_update_8105(array &$sandbox) {
  $sandbox['current'] = isset($sandbox['current']) ? ++$sandbox['current'] : 1;
  $sandbox['#finished'] = (int) $sandbox['current'] === 3;
  if ($sandbox['#finished']) {
    return "Finished at {$sandbox['current']}.";
  }
  return "Iteration {$sandbox['current']}.";
}

/**
 * Install taxonomy.module
 */
function woot_update_8106()
{
    \Drupal::service('module_installer')->install(['taxonomy']);
    return \Drupal::entityTypeManager()->getDefinition('taxonomy_term')->id();
}
