<?php

/**
 * @file
 * Provides install and update functions for drush_empty_module.
 */

/**
 * Implements hook_requirements().
 */
function drush_empty_module_requirements($phase) {
  $requirements = [];
  if (($phase === 'install') && getenv('UNISH_FAIL_INSTALL_REQUIREMENTS') === 'drush_empty_module') {
    // Fail only if the environment variable is set to a specific value.
    $requirements['drush_empty_module'] = [
      'title' => t('Drush empty module: installation failure'),
      'description' => t('Primary install requirements not met.'),
      'severity' => 2,
    ];
    $requirements['drush_empty_module_secondary'] = [
      'title' => t('Drush empty module: installation failure'),
      'description' => t('Secondary install requirements not met.'),
      'severity' => 2,
    ];
  }

  return $requirements;
}

/**
 * Fake update hook.
 */
function drush_empty_module_update_8001() {
  return 'The update ran';
}
