<?php

/**
 * @file
 * Contains woot.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function woot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the woot module.
    case 'help.page.woot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Woot Mightily.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function woot_theme() {
  $theme = [];

  return $theme;
}

/**
 * Prints the entity type ID of the taxonomy term entity type.
 *
 * @see \Unish\UpdateDBTest::testEnableModuleViaUpdate()
 * @see \Unish\UpdateDBTest::testEnableModuleViaPostUpdate()
 */
function woot_get_taxonomy_term_entity_type_id()
{
    print \Drupal::entityTypeManager()->getDefinition("taxonomy_term")->id();
}

/**
 * Implements hook_migration_plugins_alter().
 */
function woot_migration_plugins_alter(array &$migration_plugins): void
{
    if (\Drupal::state()->get('woot.test_importing_with_limit_and_feedback')) {
        // Expand the source rows to a total of 300 only for this test.
        // @see \Unish\MigrateRunnerTest::testImportingWithLimitAndFeedback()
        foreach (range(3, 300) as $nid) {
            $migration_plugins['test_migration']['source']['data_rows'][] = [
              'id' => $nid,
              'name' => "Node {$nid}",
            ];
        }
    }
}
