id: d6_syslog_settings
label: System log configuration
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: variable
  variables:
    - syslog_identity
    - syslog_facility
  source_module: syslog
process:
  identity: syslog_identity
  facility: syslog_facility
destination:
  plugin: config
  config_name: syslog.settings
