serialization.settings:
  type: config_object
  label: 'Serialization settings'
  mapping:
    bc_primitives_as_strings:
      type: boolean
      label: 'Whether to retain pre Drupal 8.3 behavior of serializing all primitive items as strings.'
    bc_timestamp_normalizer_unix:
      type: boolean
      label: 'Whether the pre Drupal 8.4 behavior of returning Unix timestamps instead of RFC3339 timestamps for TimestampItem fields is enabled or not.'
