<?php
// $Id$

/**
 * @file
 *
 */

/**
 * Implementation of hook_help().
 */
function drush_simpletest_help($section) {
  switch ($section) {
      case 'drush:test run':
        return t("Usage drush [options] test run<classes>.\n\nRun the specified specified unit tests. If <classes> is omitted, all tests are run. <classes> should be a list of classes separated by a comma. For example: PageCreationTest,PageViewTest.");
      case 'drush:test list':
        return t("Usage drush [options] test list.\n\nList the available tests. Use drush test run command to run them. ");
  }
}

/**
 * Implementation of hook_drush_command().
 */
function drush_simpletest_drush_command() {
  $items['test run'] = array(
    'callback' => 'drush_test_run',
    'description' => 'Run one or more Simpletest tests.',
  );
  $items['test list'] = array(
    'callback' => 'drush_test_list',
    'description' => 'List the available Simpletest test classes.',
  );
  return $items;
}

function drush_test_list() {
  $uncategorized_tests = simpletest_get_all_tests();
  $tests = simpletest_categorize_tests($uncategorized_tests);
  $rows[] = array(t('Group'), t('Class'), t('Name'));
  foreach ($tests as $group_name => $test_group) {
    foreach ($test_group as $test) {
      $test_info = $test->getInfo();
      $test_class = get_class($test);
      $title = $test_info['name'];
      $description = $test_info['description'];
      $rows[] = array($group_name, $test_class, $test_info['name']);
    }
  }
  return drush_print_table($rows, 0, TRUE);
}


function drush_test_run($tests = NULL) {
  simpletest_get_all_tests();
  if (is_null($tests)) {
    drush_print(t('Running all tests'));
    simpletest_run_tests($tests, 'text', FALSE);
  }
  else {
    $tests = explode(',', $tests);
    foreach ($tests as $class_name) {
      if (class_exists($class_name) || $run_all_tests) {
        $tests_list[] = $class_name;
      }
    }
    if (count($tests_list) > 0 ) {
      simpletest_run_tests($tests_list, 'text', FALSE);
    }
    else {
      drush_error(t('No test has been selected.'), 'error');
    }
  }
  print_r($_SESSION);
  return $result;
}
