drupal.settings_tray:
  version: VERSION
  js:
    js/settings_tray.js: {}
  css:
    component:
      css/settings_tray.module.css: {}
      css/settings_tray.motion.css: {}
      css/settings_tray.toolbar.css: {}
    theme:
      # @todo Set the group higher than CSS_AGGREGATE_THEME so that it overrides
      #   both jQuery UI and Classy's dialog.css, remove in
      #   https://www.drupal.org/node/1945262.
      css/settings_tray.theme.css: { group: 200 }
  dependencies:
    - core/jquery
    - core/drupal
    - core/jquery.once
    - core/drupal.ajax
