name: 'Settings Tray'
type: module
description: 'Provides a sidebar to configure blocks on the page.'
package: Core
version: VERSION
core: 8.x
dependencies:
  - drupal:block
  - drupal:toolbar
  - drupal:contextual
