id: d6_user_contact_settings
label: User contact settings
migration_tags:
  - Drupal 6
  - Content
source:
  plugin: d6_user
  constants:
    key: contact
    module: contact
process:
  uid: uid
  key: 'constants/key'
  module: 'constants/module'
  settings:
    plugin: skip_row_if_not_set
    index: contact
    source: data

destination:
  plugin: user_data
migration_dependencies:
  required:
    - d6_user
