name: Build Commands Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          path: code

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Install Drupal
        run: composer sut:si
        env:
          UNISH_DB_URL: sqlite://sites/default/files/.ht.sqlite

      - name: Drush status
        working-directory: main
        run: vendor/bin/drush --uri=dev st

      - name: Drush mk:docs
        run: composer mk:docs

#      - name: Set up Python 3.7
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Mkdocs gh-deploy
        working-directory: main/build-commands
        run: |
          env
          which mkdocs
          mkdocs gh-deploy -v --site-dir commands/10.x
