name: Build Commands Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Install Drupal
        run: composer sut:si
        env:
          UNISH_DB_URL: sqlite://sites/default/files/.ht.sqlite

      - name: Drush status
        run: ./drush --uri=dev st

      - name: Drush mk:docs
        run: composer mk:docs

      - name: Mkdocs gh-deploy
        run: |
          ls
          cd build-commands && /home/runner/.local/bin/mkdocs gh-deploy -v --force --site-dir commands/10.x
